### ISSUE TITLE
Streaming doesnt seem to be working

### ISSUE THREAD

**Issue by shivkanthb** [madroidmaq/mlx-omni-server#2]
First off, thanks for this awesome repo. Local first and openai api compatible apis is a game changer. 

Tried the following when tinkering with the chat service. 
```
response = client.chat.completions.create(
    model="mlx-community/Llama-3.2-3B-Instruct-4bit",
    messages=[
        {
            "role": "user",
            "content": "Count to 100, with a comma between each number and no newlines. E.g., 1, 2, 3, ...",
        }
    ],
    temperature=0,
    stream=True,
)

for chunk in response:
    print(chunk.choices[0].delta.content)
```

But no results till the entire thing is complete.

**Comment by madroidmaq** [comment]
Thank you for your feedback. After trying locally, I found that the project can respond normally. I have added some logs, and you can try the following steps:

```
pip install -U mlx-omni-server
```

Then enable debug log printing:

```
mlx-omni-server start --log-level debug
```

Under normal circumstances, the printed information is as follows:

<img width="1027" alt="image" src="https://github.com/user-attachments/assets/a047e45c-4faa-4713-8df5-ae2ae62da832">

**Comment by wanfade** [comment]
Same issue. 
All response via stream=true is "":
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/798b5168-29e7-406a-af96-73b9714b2701">
but correct answer when stream=false:
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/06dd2de0-f2e2-41f5-9a28-c3b40569958f">

**Comment by madroidmaq** [comment]
@shivkanthb @wanfade  I have optimized this part of the content, please try again with the latest version, and let me know if there are still issues.

**Comment by shivkanthb** [comment]
Thank you @madroidmaq for the fix. The streaming is working great now. 
Noticed something small (not related to streaming)
the `start` command is no longer valid. `mlx-omni-server` starts the server by default. Not sure if that was intentional. If so, the readme needs to be updated.
