### ISSUE TITLE
Can it support to serve inference service for multiple users concurrently ?

### ISSUE THREAD

**Issue by southkorea2013** [madroidmaq/mlx-omni-server#9]
Hi,

Could the mlx-omni-server serve the inference requests concurrently? I find the mlx_lm.server can only serve the inference requests sequentially,  I hope to host a llm server for a small team using a Mac Studio.

Thanks,
Nan

**Comment by madroidmaq** [comment]
@southkorea2013  Now the new version can specify the number of parallel processes through the `--workers` parameter, with the default being 3. Please try using the latest version (v0.2.1), and if you find any problems, please let me know.

**Comment by southkorea2013** [comment]
> @southkorea2013 Now the new version can specify the number of parallel processes through the `--workers` parameter, with the default being 3. Please try using the latest version (v0.2.1), and if you find any problems, please let me know.

Thanks. It works perfectly.
